### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/tiny-etag#1]
```
/opt/turtleio/node_modules/tiny-etag/lib/etag.js:36
			if (implicit && !cached && res.statusCode < 204 && res._
headers.etag) {
			                                                        
       ^

TypeError: Cannot read property 'etag' of null
    at ServerResponse.res.on (/opt/turtleio/node_modules/tiny-etag/lib/etag.js:3
6:67)
    at emitNone (events.js:91:20)
    at ServerResponse.emit (events.js:185:7)
    at finish (_http_outgoing.js:551:10)
    at afterWrite (_stream_writable.js:361:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by avoidwork** [comment]
Older code.
